title: CommandLang Docs
email: brzozowski.s.piotr@gmail.com
description: >-
  Docs for CommandLang

remote_theme: pmarsceill/just-the-docs

github_username:  stirante

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/stirante/cmcc-docs" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

coderay_default_lang: JSON

kramdown:
  parse_block_html: true

markdown: kramdown
url: https://docs.cmcc.stirante.com
aux_links:
  "CommandLang":
    - "https://cmcc.stirante.com"
  


# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

search_enabled: true

permalink: /:title